package Contest_2;

// Q1. Find the Difference

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more
// letter at a random position.
// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

// Constraints:
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

// Problem Link: https://leetcode.com/contest/leetcode-weekly-contest-2/problems/find-the-difference/
class Solution {
    public char findTheDifference(String s, String t) {
        int[] freq = new int[26];

        for (char ch : s.toCharArray()) {
            freq[ch - 'a']++;
        }

        for (char ch : t.toCharArray()) {
            freq[ch - 'a']--;
            if (freq[ch - 'a'] == -1)
                return ch;
        }
        return ' ';
    }
}